DROP DATABASE IF EXISTS superherodb;
CREATE DATABASE superherodb;

-- DROP DATABASE IF EXISTS testdb;
-- CREATE DATABASE testdb;


CREATE TABLE heros (
	id INTEGER NOT NULL AUTO_INCREMENT,
	hero_name VARCHAR(30) NOT NULL,
	devoured BOOLEAN NOT NULL DEFAULT false,
	PRIMARY KEY (id)
);